---
- hosts: 18.224.150.95
  become: yes
  become_method: sudo

  tasks:
   - name: Ensure wget and openjdk are installed
     ansible.builtin.apt:
       name: "{{ item }}"
       state: present
     with_items:
        - wget
        - openjdk-11-jdk
  
   - name: add jenkins gpg key
     ansible.builtin.apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key 
        state: present

   - name: add jenkins repository part 1 - create file
     ansible.builtin.file:
       path: /etc/apt/sources.list.d/jenkins.list
       state: touch

   - name: add jenkins repository part 2 - add line
     ansible.builtin.lineinfile:
       path: /etc/apt/sources.list.d/jenkins.list
       line: deb http://pkg.jenkins-ci.org/debian-stable binary/
       state: present
## A simplifier avec ansible.builtin.apt_repository

   - name: install jenkins
     ansible.builtin.apt:
      name: jenkins
      state: present
      update_cache: yes

   - name: get initial admin password
     ansible.builtin.shell: cat /var/lib/jenkins/secrets/initialAdminPassword
     register: jenkinspasswd
     changed_when: false
  
   - name: display the password
     debug: 
       var: jenkinspasswd.stdout