--- 
- hosts: 18.224.150.95
  become: yes
  become_method: sudo

  tasks:
   - name: Ensure  wget is installed
     ansible.builtin.apt:
       name: wget
       state: present

   - name: Install docker packages
     apt:
       pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
       state: latest
       update_cache: yes

   - name: Add Docker s official GPG key
     apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

   - name: Verify that we have the key with the fingerprint
     apt_key:
       id: 0EBFCD88
       state: present

   - name: Set up the stable repository
     apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present
      update_cache: yes

   - name: Install docker packages
     apt:
        pkg:
         - docker-ce
         - docker-ce-cli
         - containerd.io
        state: latest
        update_cache: true
  
   - name: Install docker-compose
     get_url: 
      url : https://github.com/docker/compose/releases/download/v2.0.0-rc.3/docker-compose-linux-amd64
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x'

   - name: grant execution 
     shell: sudo chmod +x /usr/local/bin/docker-compose
