---
- hosts: afrix
  become: yes
  become_method: sudo

  tasks:
  - name: Install apache
    ansible.builtin.apt: 
     name: "{{ packages }}"
    vars:
     packages:
      - apache2
      - apache2-utils

  - name: Install mariadb
    ansible.builtin.apt: 
      name: "{{ packages }}"
    vars:
     packages:
      - mariadb-server
      - mariadb-client


  - name: Install php7.4
    ansible.builtin.apt:
      name: "{{ packages }}"
    vars:
      packages:
        - php7.4
        - libapache2-mod-php7.4
        - php7.4-mysql
        - php7.4-common
        - php7.4-cli
        - php7.4-json
        - php7.4-opcache
        - php7.4-readline
        - php7.4-fpm
        - php7.4-mbstring
     
  - name: Add php7.2 repository
    ansible.builtin.apt_repository:
     repo: ppa:ondrej/php  

  - name: Install php7.2
    ansible.builtin.apt:
      name: "{{ packages }}"
    vars:
      packages:
        - php7.2
        - libapache2-mod-php7.2
        - php7.2-mysql
        - php7.2-common
        - php7.2-cli
        - php7.2-json
        - php7.2-opcache
        - php7.2-readline
        - php7.2-fpm
        - php7.2-mbstring

  - name: Creating file echo
    ansible.builtin.copy:
      dest: "/var/www/html/mari"
      content: | 
                "<?php phpinfo(); ?>"
